- hosts: 100slices
  remote_user: root
  tasks:
  - name: Install Apache. 
    apt:
            name: apache2
            update_cache: yes
  - name: Launch Apache.
    service:
            name: apache2
            state: started
            enabled: yes
